
language: node_js
node_js:
  - "13"
git:
  depth: 3
  quiet: true
before_install:
  - rm -rf .git
  - npm set audit false
install:
  - git clone https://github.com/sukkaw/hexo-theme-doku.git themes/doku
  - rm -rf themes/doku/.git
  - cp theme_config.yml themes/doku/_config.yml
  - npm i
script:
  - hexo g
cache: npm
deploy:
  provider: pages
  local-dir: public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  fqdn: https://doku.skk.moe
  email: $GITHUB_EMAIL
  name: $GITHUB_USER
  keep-history: true
  on:
    branch: master
